### ISSUE TITLE
Cannot scroll to bottom of screens when image closed

### ISSUE THREAD

**Issue by bermanapps** [thesmythgroup/easy_image_viewer#32] opened 2023-01-09 18:54 UTC
Hi
I'm using this in my flutter app.
However, after I click on the image, and it opens in a new window, the image works and zooms great.
However, when I exit the image (with the x in the top), from now on, on all my other screens, I'm not able to scroll to the bottom. The last few lines of the screen are cut off at the bottom
Very strange.

**Comment by jfahrenkrug** [comment] 2023-01-09 19:24
Thank you for reporting this issue. Do you mind using the bug ticket template and providing the information it's requesting (like operating system etc). Could you maybe also do a screen recording of the bug and post it here? Thank you! That'll help us investigate.

**Comment by bermanapps** [comment] 2023-01-09 19:30
Here is my flutter class:


class ImageViewerScreen extends ConsumerStatefulWidget {
  const ImageViewerScreen({
    Key? key,
  }) : super(key: key);

  @override
  ConsumerState createState() => _ImageViewerScreenState();
}

class _ImageViewerScreenState extends ConsumerState<ImageViewerScreen> {
  final titleController = TextEditingController();
  final detailsController = TextEditingController();

  @override
  Widget build(BuildContext context) {
    titleController.text = 'Percription for 3/4/2022';
    detailsController.text =
        'Thisofsoor turpose ofsno was imputted fthe purpose ofimputted for the purpose of everyone.';

    return Scaffold(
      appBar: AppBar(
        title: Text('Image details'),
        actions: [
          IconButton(
            icon: Icon(
              Icons.delete,
              color: Colors.white,
            ),
            onPressed: () {
              // do something
            },
          )
        ],
      ),
      body: ListView(
        shrinkWrap: true,
        // padding: EdgeInsets.all(15.0),
        children: [
             Padding(
            padding: const EdgeInsets.all(8.0),
            child: Container(
              width: MediaQuery.of(context).size.width,
              child: GestureDetector(
                onTap: () {
                  showImageViewer(context,
                      Image.network("https://picsum.photos/250?image=9").image,
                      swipeDismissible: false, doubleTapZoomable: true);
                },
                child: FadeInImage.memoryNetwork(
                  placeholder: kTransparentImage,
                  image: 'https://picsum.photos/250?image=9',
                  fit: BoxFit.fill,
                ),
              ),
            ),
          ),
          EditableTextInputWidget('Title', titleController),
          EditableTextInputWidget('Description', detailsController),
          // SizedBox(height: 50,),
        ]),
      );
    // );
  }
}

**Comment by bermanapps** [comment] 2023-01-09 19:31
Here is a video

https://user-images.githubusercontent.com/28511238/211392103-d2add1d6-8954-4ca2-9424-b29641149f7b.mp4

**Comment by jfahrenkrug** [comment] 2023-01-09 19:40
That's super helpful, thanks so much! I'll take a look as soon as I can.

**Comment by jfahrenkrug** [comment] 2023-01-11 10:55
@bermanapps I could not reproduce your issue. (See attached video). Could you please provide a complete sample application that demonstrates the issue you are seeing? Then I'm happy to take another look. Thanks!


https://user-images.githubusercontent.com/16358/211788747-1bd0778a-2dc5-43ac-bdde-2ac8b95fa0d0.mp4

**Comment by jfahrenkrug** [comment] 2023-03-02 14:30
@bermanapps I'll close this issue for now. If you get around to providing a sample project I'm happy to take another look. Thanks!

**Closed by jfahrenkrug** 2023-03-02 14:30 UTC
Labels: bug, good first issue
